### ISSUE TITLE
Publish to winget

### ISSUE THREAD

**Issue by ptrdom** [VirtusLab/scala-cli#1181]
Since [winget](https://docs.microsoft.com/en-us/windows/package-manager/winget/) is the MS endorsed package manager for Windows, it would be great if scala-cli was available on it. Eventually it might have enough functionality to fully replace Chocolatey, supporting both in the meanwhile would be ideal.

**Comment by He-Pin** [comment]
![image](https://user-images.githubusercontent.com/501740/195088987-0ad327f8-b79c-4d56-b7d4-8a6ab1e449ec.png)
Sbt is published to winget now.

**Comment by Gedochao** [comment]
For future reference, transcribing the screenshot to characters:
```
C:\Users\hepin>winget install scala-cli
尝试更新源时失败: winget
找不到与输入条件匹配的程序包
```

To my knowledge, the rough translation to English would be:
```
Failed while attempting to update: winget
Could not find a package for the given input.
```

@He-Pin 
Btw. when providing examples in Mandarin, please try to at least give rough translations to English when able. =) 
At the very least, please paste the 汉字 characters instead of just a screenshot so it's easier for people to use an online translator.
It might speed us up a bit. 
(the full context in Mandarin is still helpful)

**Comment by He-Pin** [comment]
Hi， which means it can't find the `scala-cli` package in winget repo. 
Sorry for not describe it in English.
