### ISSUE TITLE
Build Linux aarch64 binaries from M1 CI

### ISSUE THREAD

**Issue by alexarchambault** [VirtusLab/scala-cli#1279]
We could build Linux aarch64 binaries for Scala CLI using docker on the M1 CI. It should be faster than [using aarch64 emulation on GitHub actions runners](https://github.com/uraimo/run-on-arch-action), like coursier does for example, and turned up to be too slow to build Scala CLI binaries (the jobs were just stuck…)

**Comment by kubukoz** [comment]
If we have M1 CI available, please do mac binaries as well 😅

**Comment by lwronski** [comment]
There is a new dedicated launcher of scala-cli `0.1.15` for M1 users. You can find it [here](https://github.com/VirtusLab/scala-cli/releases/download/v0.1.15/scala-cli-aarch64-apple-darwin.gz).

In the future, it will be added some packages installation M1. For now, it is available only launcher.

**Comment by lwronski** [comment]
I opened two issues with adding support to install scala-cli for m1 in `brew` and `sdkamn`

- https://github.com/VirtusLab/scala-cli/issues/1429
- https://github.com/VirtusLab/scala-cli/issues/1430

I will close this issue because now the m1 launcher is available in release [assets](https://github.com/VirtusLab/scala-cli/releases/tag/v0.1.15).
