### ISSUE TITLE
`//> using option "--explain"` does nothing

### ISSUE THREAD

**Issue by Kordyjan** [VirtusLab/scala-cli#1285]
**Version(s)**
`0.1.12`

**Describe the bug**
`//> using option "--explain"` doesn't change the compilation output. Probably it has the same root cause as #1023. The problem goes away if we run scala-cli with `--server=false`. 

**To Reproduce**
explain.scala:
``` scala
//> using option "--explain"

class A

val i: Int = A()
```

Run `scala-cli compile explain.scala`. The output will be:

```
[error] ./explain.scala:5:14: Found:    A
[error] Required: Int
[error] val i: Int = A()
[error]              ^^^
Error compiling project (Scala 3.1.3, JVM)
Compilation failed
```

**Expected behaviour**

The output should look like this:
```
-- [E007] Type Mismatch Error: /Users/pmarks/projs/rep/explain.scala:5:14 ------
5 |val i: Int = A()
  |             ^^^
  |             Found:    A
  |             Required: Int
  |-----------------------------------------------------------------------------
  | Explanation (enabled by `-explain`)
  |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  |
  | Tree: new A()
  | I tried to show that
  |   A
  | conforms to
  |   Int
  | but the comparison trace ended with `false`:
  |
  |   ==> A  <:  Int
  |   <== A  <:  Int = false
  |
  | The tests were made under the empty constraint
   -----------------------------------------------------------------------------
   ```

**Comment by lwronski** [comment]
@Kordyjan Thanks for reporting. I want to summarize this issue. 

First of all, the `explain` message which you mention is generated [here](https://github.com/lampepfl/dotty/blob/8de6d88450f89cb3d2dc779b880dae1a92deef70/sbt-bridge/src/dotty/tools/xsbt/DelegatingReporter.java#L40) in `scalac` and set to a  field `rendered` in `Problem` class.

From the `bloop` side, the `rendered` message are available and ready to use but it is skipped. In `BSP` there is no reasonable field in [Diagnostic](https://github.com/lwronski/build-server-protocol/blob/8281ddc9f45f4f725ec867cbbf559c94e8ac6fa5/bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/Diagnostic.java#L10) class to send `rendered` message. The `rendered` content isn't so important to the IDE and is probably for this reason the message isn't sent anywhere from `bloop`.

In scala-cli which uses `bloop` under the hood, the rendered message isn't available because `bloop` doesn't send this message. 

There are at least two solutions of this problem:
-  modification of the BSP protocol to send `rendered` message to `scala-cli`
-  if the user passes the `explain` option to scala-cli, the `scalac` compiler will be automatically used, i.e. the `--server=false` flag will be set

**Comment by tgodzik** [comment]
It's also a bit weird that `explain` message is only available in the rendered message and not in for example usual `message` field. This doesn't allow tools to sensibly use that additional message and render in their own style. It's either you use render or you don't get it.

I would be better if this was added to some other field or as additional diagnostics. Not sure currently what would be the best solution, but it fits into the whole structured errors and actionable diagnostics debacle. Ideally `explain` message would be a field that is always available without running a second compilation or modifying the whole build definition.
