### ISSUE TITLE
No sensible difference between commands doctor, about, and version

### ISSUE THREAD

**Issue by julienrf** [VirtusLab/scala-cli#1665]
**Is your feature request related to a problem? Please describe.**

Currently (`scala` 0.1.18 installed via `cs install scala-experimental`), the documentation says the following:

~~~ text
Doctor commands:
  doctor  Print details about this application

Miscellaneous commands:
  about    Print details about this application
  version  Print version
~~~

It is not clear what are the differences between `doctor`, `about`, and `version`.

I tried all of them and I got the following output:

~~~ text
$ scala doctor
Your scala version (0.1.18) is current.
scala can be updated by your package manager since it is correctly installed in only one location: .
Your scala is a native application.

$ scala about
Scala code runner version: 0.1.18
Scala version (default): 3.2.1
$ scala version
Scala code runner version: 0.1.18
Scala version (default): 3.2.1
~~~

**Describe the solution you'd like**

I suggest keeping the behavior of `version` as it is, but improving its documentation to the following:

~~~ text
Print the version of the scala runner and the default Scala version (unless specified in the project).
~~~

I suggest removing the `about` command, or renaming `doctor` into `about` (so, removing `doctor`) because “about” is more self-explanatory or intuitive to me (but that might be purely subjective).

**Comment by prolativ** [comment]
Was `doctor` command inspired by metals doctor? This thought made me realize that it would make sense to have a command not only to give a user some information about the scala runner itself, but also about the current configuration of a given project. But I would probably call it something like `project` or `project-info` instead of `doctor`.
Then running `scala project .` would read the using directives from all the sources and then print out the scala version, declared dependencies, compiler options etc., taking into account possible differences between configurations for different target platforms

**Comment by tgodzik** [comment]
> I suggest removing the about command, or renaming doctor into about (so, removing doctor) because “about” is more self-explanatory or intuitive to me (but that might be purely subjective).

Makes sense from my side. And we should probably also include something like @prolativ suggested, but that should be a separate feature request.

**Comment by Gedochao** [comment]
@prolativ I extracted the `project` sub-command feature into a separate issue: #1722 

@julienrf after some offline discussion, it seems we'll proceed with this ticket as follows:
- the `about` sub-command will be merged back to the `version` sub-command and removed
- the `doctor` sub-command will be removed, while its current features will be delivered through other means at a later date (possibly expanding the existing actionable diagnostics)
  - this is based on the current approach of making Scala CLI interactive, rather than something you should run the `doctor` sub-command with to see what's wrong
- this way, we'll go down to just having the `version` sub-command

**Comment by julienrf** [comment]
Thank you for addressing this issue promptly!
