### ISSUE TITLE
Option `-save` is not supported

### ISSUE THREAD

**Issue by julienrf** [VirtusLab/scala-cli#1670]
**Is your feature request related to a problem? Please describe.**

The current `scala` runner (based on Scala 2.13) does support a [`-save`](https://github.com/scala/scala/blob/7ab7c953d173fb82673badf091b48222874b0bc0/src/compiler/scala/tools/nsc/GenericRunnerCommand.scala#L98) option.

The experimental `scala` runner (based on Scala CLI) does not recognize that option:

~~~ text
$ scala -save test.scala 
Unrecognized argument: -save

To list all available options, run
  /home/julien/.local/share/coursier/bin/.scala.aux --help
~~~

**Describe the solution you'd like**

For the sake of compatibility with the current runner, it would be great to recognize the `-save` option. As far as I understand, Scala CLI now always behaves like the current `scala -save`, so the option is not necessary anymore. Therefore, it could simply print a warning like “Unnecessary option: -save. This option is always enabled.”

**Comment by Gedochao** [comment]
> As far as I understand, Scala CLI now always behaves like the current scala -save, so the option is not necessary anymore.

Actually, it seems that part isn't entirely true.
There doesn't seem to be any official docs on the `-save` (and tied `-nosave`) options for the old `scala` command beyond what's in the runner code itself.
For context, here are the relevant code bits:

- Scala 2: https://github.com/scala/scala/blob/f8d3c4d57854f08ae261b65d87005de004e8b2c8/src/compiler/scala/tools/nsc/GenericRunnerSettings.scala#L60
- Scala 3: https://github.com/lampepfl/dotty/blob/main/compiler/src/dotty/tools/MainGenericRunner.scala#L142

Looking at the actual behaviour:
```bash
▶ tree -a
# .
# └── smth.scala
#
# 0 directories, 1 file
▶ scala -save smth.scala
# Hello
▶ tree -a
# .
# ├── smth.jar
# └── smth.scala
# 
# 0 directories, 2 files
▶ scala smth.jar
# Hello
```
It seems that the `-save` option forces a compiled `jar` to be saved in the `cwd`, while `-nosave` overrides it and prevents the jar being saved (for whatever reason).

Now, this looks like a way to combine the `run` and `package --lib` subcommands of Scala CLI.
We could theoretically support it by running the 2 subcommands one after another (that'd be a quick bandaid) or (preferably) combine both effects in a single build.

> Therefore, it could simply print a warning like “Unnecessary option: -save. This option is always enabled.”

In this context, that wouldn't be true. We could always just not support it if it's not actually needed and print a warning like `Deprecated option '-save' ignored.`, so that it doesn't fail the build.

@julienrf thoughts? Is this option necessary?

**Comment by Gedochao** [comment]
Also, a side note - it seems that what I mentioned above would also require us to implement #1641, so I'm tagging it as `SIP` as well...

**Comment by julienrf** [comment]
I think the fact that it saves the compiled code as a .jar is an “implementation detail”. But maybe not. Maybe some people are relying on the produced jar. In that case, I think a warning saying that this option is ignored but the compilation artifacts _are_ saved (in `.scala-build/`) for reuse, and that a .jar can be produced with the command package would be enough.

**Comment by Gedochao** [comment]
We could even suggest running a subsequent `package --lib` in the warning, too, in case someone actually needs that jar... That'd reuse whatever is in `.scala-build/`, so it wouldn't be much slower beyond the necessity of running another command.
I guess that if it's a niche use case, maybe that'd be enough.
