### ISSUE TITLE
`sc` Files with main Methods inside objects

### ISSUE THREAD

**Issue by LaurenceWarne** [VirtusLab/scala-cli#1675]
**Version(s)**
`0.1.18`

**Describe the bug**
`--main-class-ls` does not appear to pick up main methods defined within an object with scala scripts (`sc` files), though it does with `.scala` files (of course I can use `@main` instead - I'm just a bit curious whether this is intended).

**To Reproduce**
Create a directory structure like so:
```
├── file1.sc
└── file2.scala
```

With `file1.sc`:
```scala
object file1obj {
  def main(args: Array[String]) = {
    println("main 1")
  }
}
```
`file2.scala`:
```scala
object file2obj {
  def main(args: Array[String]) = {
    println("main 2")
  }
}
```

Then:
```
$ scala-cli file1.sc --main-class-ls   
file1_sc
$ scala-cli file2.scala --main-class-ls
file2obj
```

**Expected behaviour**
That the first command returns `file1obj` in addition to `file1_sc` (or is this intended behaviour)?

Thanks

**Comment by julienrf** [comment]
I am posting a link to the discussion https://github.com/VirtusLab/scala-cli/discussions/1668 just to link things

**Comment by lwronski** [comment]
Hi @LaurenceWarne  Thanks for reporting. 

The files ending with the `.sc` extension are evaluated as Scala Scripts; that is, when you have the following test.sc file:

```
$ cat test.sc
println("Hello")
```

 Scala CLI wrap the code into a main object and then run it. In the `.scala-build` file, you can find the generated file:
 ```
$ cat .scala-build/project_103be31561-70dbe69021/src_generated/main/test.scala




object test {
/*<script>*/
println("Hello")
/*</script>*/ /*<generated>*/
def args = test_sc.args$
  /*</generated>*/
}

object test_sc {
  private var args$opt0 = Option.empty[Array[String]]
  def args$set(args: Array[String]): Unit = {
    args$opt0 = Some(args)
  }
  def args$opt: Option[Array[String]] = args$opt0
  def args$: Array[String] = args$opt.getOrElse {
    sys.error("No arguments passed to this script")
  }
  def main(args: Array[String]): Unit = {
    args$set(args)
    test.hashCode() // hasCode to clear scalac warning about pure expression in statement position
  }
}
```

When you try to search for the main classes in your Scala Script file, it's found only `file1_sc` because your main class was wrapped into a new main class, which is named as the file name with suffix `_sc`.

Yes, `--main-class-ls` works as intended for Scala scripts. Unfortunately, nested main classes are not supported by Scala.

**Comment by LaurenceWarne** [comment]
> Unfortunately, nested main classes are not supported by Scala.

I see, I didn't know that.  I'll close since it's expected behaviour (:
