### ISSUE TITLE
`project` subcommand

### ISSUE THREAD

**Issue by Gedochao** [VirtusLab/scala-cli#1722]
**Is your feature request related to a problem? Please describe.**
For larger projects with multiple dependencies it may be hard to grasp all of the relevant configurations, dependencies declared in multiple files, etc. 
It'd be useful to have a sub-command for printing the details of a given Scala CLI project.

**Describe the solution you'd like**
Something like this:
```bash
$ scala-cli project .
# Scala version used: 3.2.1
# dependencies:
#   com.lihaoyi::os-lib:0.8.1
#   com.lihaoyi::pprint:0.8.1
# Scala compiler options
#    -release 11
#   -new-syntax
# ...
```
We could give the summary of all of the dependencies, compiler options, platform, Scala & JVM versions and everything else configured by using directives in the project pass as inputs.

**Additional context**
Created from a comment posted by @prolativ in https://github.com/VirtusLab/scala-cli/issues/1665#issuecomment-1342679214

**Comment by prolativ** [comment]
Some things to consider:
* Is `project` the best name or can we come up with something better? Is this the first word that comes to people's minds when they think `I would like to print out all the directives that are taken into account when compiling/running/publishing the given sources`?
* In case of compiler options specifically it would be probably easier not to split them into multiple lines. Otherwise we would have to have some extra logic telling us whether there should be a new line e.g. between `-release` and `11` or not
* By default should we only show the directives for the default target or a matrix of configurations for each combination of JVM/native/js X main/test X scala3/scala2_13/... for which the given project is written? `project` command (or whatever we call it) should probably also accept flags like `-S 3`, `--js` etc. to filter this matrix and show only the configuration for a specific target

**Comment by rmgk** [comment]
> Is project the best name or can we come up with something better? Is this the first word that comes to people's minds when they think I would like to print out all the directives that are taken into account when compiling/running/publishing the given sources?

Just as a random personal data point, what I would think of is something like `export --json` or maybe for something more people friendly `export --project-description`.
But the kind of information that is exported seems like it should be the same that is used in the sbt or mill exports.

**Comment by tgodzik** [comment]
@rmgk Raised it as a separate issue https://github.com/VirtusLab/scala-cli/issues/1791 but could essentially be the same as project. `scala-cli project --json` maybe?

Edit: Actually, we already have export so that should be `export --json` I think.

**Comment by rmgk** [comment]
> Edit: Actually, we already have export so that should be `export --json` I think.

Ah, yeah, I should have been a bit more clear about that.
It is because there is an `export` command, that I would have expected it to be `export --whatever` to get project output in any format.

The proposed `project` command in this in issue uses some seemingly unstructured output format as an example, but I still would expect that under `export` (as in exporting the data to the user for information purposes), because the presented data is the same as would be exported to anything else. 
While just `project` seems to not fit that context for me. In particular because it is not clear why that would be a project description. `describe` might be a better term if my interpretation of `export` seems to far-fetched :-)

**Comment by prolativ** [comment]
`export` seems to do something more than just print the project configuration in a given format to stdout. It creates a new directory structure for your sources and copies them to the new locations on disk together with the generated `build.sbt` / `build.sc` file.
