### ISSUE TITLE
Allow users to disable dependency updates

### ISSUE THREAD

**Issue by tgodzik** [VirtusLab/scala-cli#1825]
**Is your feature request related to a problem? Please describe.**
Currently if a user wants to keep a certain version of the dependency they will get a warning that it's outdated, but it might not always be possible to update it.

**Describe the solution you'd like**
Let's at a very minimum add and option to disable these warnings, we can follow up with something more concrete

**Describe alternatives you've considered**
Disable all the actionable diagnostics with `scala-cli config actions false`

**Additional context**
https://github.com/VirtusLab/scala-cli/issues/1822

**Comment by julienrf** [comment]
Related to that, I would like to share my experience.

I use a couple of Scala scripts to automate some tasks. These scripts are distributed in the form of source files. Once a script is implemented, all I want to do is to run it with `scala run my-script.scala`. It is important to note that because it is a script, it is distributed as a source file (not as a compiled jar file), so this is different from the usual workflow where we have a development cycle well separated from the usage cycle.

When I do that with Scala CLI, because of that mechanism that checks for dependency updates, when I just want to run the script, the Scala CLI tries to resolve things from the Internet (to check for possible dependency updates) and then always prints the warnings. This slows down the execution time (because of the network IO), and this also confuses the non-developer users of the script, who don’t know much about Scala but just need to use the script.

Ultimately, I really think the `run` command should, by default, not check for dependency updates. I could see some value in printing those warnings when running the command `compile` maybe (because in such a case it is clear that we are in the development cycle of the program, not in the usage cycle), but I wonder if that should be an explicit command instead (`check-dependencies`)? By the way, I don’t see a huge value in being notified that there is a new version of a dependency, however, I do see a huge value in being notified that the versions of some library dependencies are affected by a security vulnerability. So, I wonder if that should be the focus instead.

**Comment by Gedochao** [comment]
@julienrf I'm not so sure about the `run` sub-command, as it is the default sub-command when inputs are passed to Scala CLI... but I would agree that maybe we could skip checking dependency updates when `shebang` is run. That would cover your use case with scripts, no?

**Comment by julienrf** [comment]
Yes, that would cover my use case, but I still think it would be better to have both `run` and `shebang` consistent together in this regard.

**Comment by Gedochao** [comment]
I get the feeling that whatever is the default when run with Scala CLI should give as much feedback as possible to the user... and since `run` is the default, I'd hesitate to stop checking for dependencies there...
It seems that for the time being we're adding a flag to suppress the warning in #1848, I'll discuss with the team how to handle it best long term
