### ISSUE TITLE
Running scripts (.sc) that contain effect systems such as Cats and ZIO could use some specific support

### ISSUE THREAD

**Issue by robknapen** [VirtusLab/scala-cli#1895]
Currently a simple ZIO program such as this:

```
//> using scala "3.2.2"
//> using lib "dev.zio::zio::2.0.9"

import zio._

object HelloApp extends ZIOAppDefault:
  def run = Console.printLine("Hello, World!")

```

Does not produce any output when run with scala-cli if it is in a '.sc' file, but works properly when it is in a '.scala' file. The behaviour can be expected, but can also surprise users. Perhaps scala-cli can provide some helpful hints when it encounters this, or work in such a way that it still runs the effects.

**Comment by Gedochao** [comment]
This is similar to how an explicit main method declaration will be ignored unless explicitly called in an `.sc` script.

```scala title=script.sc
@main def main(): Unit = println("Hello, World!")
```

As you say, this is expected, since scripts already have a main method and Scala CLI does not inspect for a nested one.

Both that and the ZIO issue mentioned here could probably be solved by the `@entrypoint` annotation (refer to #1818), but I don't think we'll be adding that soon... not until macro annotations are considered stable in Scala 3, I think (which I'm not sure when will it happen).

**Comment by Gedochao** [comment]
Seems we will not support this for now, closing this issue.
