### ISSUE TITLE
Provide a way to extract all directives declared across different scala files into a single file

### ISSUE THREAD

**Issue by calvinlfer** [VirtusLab/scala-cli#2104]
**Is your feature request related to a problem? Please describe.**
I found that allowing directives all over the place got confusing really quick (but I understand its good for prototyping). It would be extremely useful to have a command in order to centralize all directives into a single file (like project.scala)

**Describe the solution you'd like**
Run a command like `scala-cli --centralize-directives` in order for the process to happen automatically

**Describe alternatives you've considered**
Maniually going through each file and removing the directives from there and placing them into `project.scala`

**Additional context**
Currently, Scala CLI produces a warning with suggestions to place the directives in `project.scala` - we need to make it actionable (so you can click and apply the changes or run a separate command in order to do this).

https://twitter.com/cal_fern/status/1655912142753677314

**Comment by Gedochao** [comment]
We technically have been tracking this under #1489, but maybe it makes sense to have a separate ticket for it, so that we don't forget about it...
There's also been an attempt at implementing it in #1627, but the PR didn't get finished and has unfortunately grown a bit stale...

Thanks for raising this, nonetheless.

**Comment by mpkocher** [comment]
I kinda understand the motivation for this, but surface area of functionality of `scala-cli` seems to be growing without bound. I think it's useful for the `scala-cli` team to suggest other workarounds instead of always saying yes and adding new features. 

A reasonable workaround would be to use a little bit of shell code using `grep` and `uniq` to centralize the dependencies into a `project.scala` file. Similarly, using `grep -v` could strip out the directives of scala files. I suspect a couple of lines of shell code munging accomplishes 90% of the requirements that are described above without adding any cognitive overhead or technincal complexity to `scala-cli`.

Also, I'm not sure that `scala-cli` should get too tangled up in tasks (e.g., refactoring dependencies) that might be better suited for your text editor or IDE.

**Comment by calvinlfer** [comment]
in my humble opinion, this feature pushes people over the threshold of using Scala CLI only to do intial prototyping and allows them to easily continue using Scala CLI as a build tool past the prototyping stage. 

Can you do this manually? sure, but why not give people one more reason by making it easier for them

**Comment by tgodzik** [comment]
> I kinda understand the motivation for this, but surface area of functionality of `scala-cli` seems to be growing without bound. I think it's useful for the `scala-cli` team to suggest other workarounds instead of always saying yes and adding new features.
> 

I understand your worries, but we do try to limit the features to the ones that we deem necessary or ones that improve the user experience. And anything we experiment with we keep under experimental and try to separate it from any existing features.

> A reasonable workaround would be to use a little bit of shell code using `grep` and `uniq` to centralize the dependencies into a `project.scala` file. Similarly, using `grep -v` could strip out the directives of scala files. I suspect a couple of lines of shell code munging accomplishes 90% of the requirements that are described above without adding any cognitive overhead or technincal complexity to `scala-cli`.

Sure, but we are showing a warning for the user here, so we should provide an easy way to fix that. Not every user will be able to do it via other tools.

> 
> Also, I'm not sure that `scala-cli` should get too tangled up in tasks (e.g., refactoring dependencies) that might be better suited for your text editor or IDE.

Yes and no, the editors usually know a lot about code, not so much about build definition especially that there is quite a few tools out there.
