### ISSUE TITLE
Syntax coloring for using directives without double quotes  in Metals

### ISSUE THREAD

**Issue by lwronski** [VirtusLab/scala-cli#2178]
**Is your feature request related to a problem? Please describe.**
When the scala-cli doesn't require double quotes for using directives, Metals color keywords with the same color as values.
<img width="555" alt="Screenshot 2023-06-01 at 10 43 07" src="https://github.com/VirtusLab/scala-cli/assets/46607934/64b82cea-a6a3-4150-8903-b7a8b2adc5a1">

```
//> using dep com.lihaoyi::os-lib:0.9.1
//> using test.dep org.scalameta::munit::0.7.29
//> using toolkit latest

object Hello extends App {
  println("Hello")
}
```

**Describe the solution you'd like**

Values are coloured with different color than keywords.

**Comment by lwronski** [comment]
cc: @jkciesluk

**Comment by tgodzik** [comment]
Och, we might need to update it in the VS Code extension if anyone has time.

**Comment by tgodzik** [comment]
https://github.com/scala/vscode-scala-syntax/blob/78750edc8babd117616290e507697a46cbadc85a/src/typescript/Scala.tmLanguage.ts#L1020

**Comment by jkciesluk** [comment]
Fixed it for semantic highlight in https://github.com/scalameta/metals/pull/5301

![image](https://github.com/VirtusLab/scala-cli/assets/72950514/8672aea6-c1e6-4ae2-be97-4fee37307936)
What do you think?

We still need to fix it in https://github.com/scala/vscode-scala-syntax/blob/78750edc8babd117616290e507697a46cbadc85a/src/typescript/Scala.tmLanguage.ts#L1020, since it won't work with semantic highlighting turned off

**Comment by lwronski** [comment]
@jkciesluk Thank you for working on this issue, it's really cool. It looks nice to me. @MaciejG604, do you have any thoughts?

**Comment by MaciejG604** [comment]
Nothing to add from me, looks good. Thanks @jkciesluk!

**Comment by tgodzik** [comment]
Fully released and available at https://github.com/scala/vscode-scala-syntax/releases/tag/0.5.7
