### ISSUE TITLE
XDG specification support

### ISSUE THREAD

**Issue by untainsYD** [VirtusLab/scala-cli#2371]
In Linux, scala-cli generates files in the home user directory, such as ~/.dotty_history, when the scala-cli repl command is invoked. It would be more appropriate to adhere to the XDG specification and create the .dotty_history file within the `$XDG_CACHE_HOME/repl/` directory or a similar location.

*NOTES: i couldn't find any information in the documentation on specifying the scala-cli tool's cache directory.*

**Comment by SethTisue** [comment]
Note that `~/.dotty_history` is coming from the Scala 3 REPL, rather than from scala-cli per se (which is merely launching that REPL). See https://github.com/lampepfl/dotty/blob/450d233ed9a39b67c60ed7fd9052d235893921f4/compiler/src/dotty/tools/repl/JLineTerminal.scala#L63

Similarly, the Scala 2 REPL writes a `~/.scala_history_jline3`; the ticket on that is https://github.com/scala/bug/issues/12627

**Comment by untainsYD** [comment]
> See https://github.com/lampepfl/dotty/blob/450d233ed9a39b67c60ed7fd9052d235893921f4/compiler/src/dotty/tools/repl/JLineTerminal.scala#L63
> 
> Similarly, the Scala 2 REPL writes a `~/.scala_history_jline3`; the ticket on that is [scala/bug#12627](https://github.com/scala/bug/issues/12627)

Oh, i see, thank you for your answer!
