### ISSUE TITLE
automatic scala 3 compiler library does not match compiler version

### ISSUE THREAD

**Issue by bishabosha** [VirtusLab/scala-cli#262]
### scala-cli version

v0.0.7

### minimal example

```scala
import dotty.tools.dotc.config.Properties.versionString

println(s"Scala $versionString")
```

if I run this in scala-cli with `-S 3.1` then it prints `Scala version 3.0.0`, I have to explicitly add `using lib org.scala-lang::scala3-compiler:3.1.0` to get the library that matches the compiler version

**Comment by romanowski** [comment]
The code should not compile in the first place, since compiler internals should not be visible on the classpath without a declaration. 

The fact that the code works is caused by us adding https://github.com/Virtuslab/pretty-stacktraces to the classpath to nicely prints exceptions and it adds transitive dependency to the compiler in 3.0 (through tasty-inspector). I think we need to change that behaviour.

**Comment by lwronski** [comment]
Hi @bishabosha, thanks for reporting. 

From ScalaCLI `0.1.5` was removed pretty-stack traces from classpath, so transitive dependency to the compiler in 3.0 (through tasty-inspector) is isn't available. 

so this piece of code is not compiling from now.  IMO scala-cli should not add automatically dependency to the compiler so it is correct behavior. 

Please feel free to reopen the issue, if you have any suggestions that ScalaCLI should add a dependency to the compiler.
