### ISSUE TITLE
It should be possible for SemanticDB `targetroot` to be different from `projectWorkspace/.scala-build`

### ISSUE THREAD

**Issue by tgodzik** [VirtusLab/scala-cli#2646]
**Version(s)**
1.1.0

**Describe the bug**
Currently, if we specify for Metals the flag for changing the location for `scala-build` the sourceroot option for semanticdb will also be changed to that directory. This might cause issues when reading semanticdb as sourceroot will not be a parent of the sources, which is expected.

**To Reproduce**
Open Metals after running setup-ide with changing build directory to some temporary folder.

**Expected behaviour**
Sourceroot should be sent to some parent directory.

https://github.com/scalameta/metals/issues/5748

**Comment by Gedochao** [comment]
So from Scala CLI's/compiler's point of view, this is not a bug, not really.
By default SemanticDB files follow the `-d` option in the compiler, which means they are output alongside the compiled class files. Which is why Scala CLI puts the SemanticDB files in the `.scala-build` directory.
SemanticDB allows to override that separately from the compiled classes output by setting the `targetroot` (not `sourceroot`, that's separate) value, but the syntax for setting `targetroot` is a bit confusing and different depending on the compiler version and how the SemanticDB plugin is being passed.

@tgodzik #2692 adds a `--semanticdb-targetroot` option, which provides a unified syntax for passing the `targetroot` from the command line. I believe this should be enough to address the tied issue in Metals.
