### ISSUE TITLE
Scala-cli does not download some dependencies

### ISSUE THREAD

**Issue by cebaraldi** [VirtusLab/scala-cli#2647]
**Version(s)**
Scala 3.3.1 and Scala 2.13.12, I could try the entire cascade by using the directive --scala, when calling scala-cli.

**Describe the bug**

**To Reproduce**
That is easy: Just call "scala-cli repl" with an appropriate "--dep" directive, for instance:

scala-cli repl --scala 3.3.1 --dep commons-net::commons-net:3.10.0
Downloading 2 dependencies
[error]  Error downloading commons-net:commons-net_3:3.10.0
  not found: C:\Users\ceb\.ivy2\local\commons-net\commons-net_3\3.10.0\ivys\ivy.xml 
  not found: https://repo1.maven.org/maven2/commons-net/commons-net_3/3.10.0/commons-net_3-3.10.0.pom
  not found: C:\Users\ceb\AppData\Local\ScalaCli\cache\local-repo\1.1.0\commons-net\commons-net_3\3.10.0\ivys\ivy.xml
  No fallback URL found

**Expected behaviour**
"Scala-cli" should start inside the REPL without error messages. Maybe the dependency is unavailable? Unfortunately this information cannot be extracted neither from Maven (https://mvnrepository.com/artifact/commons-net/commons-net) nor from the error message above.

Scala-cli

**Comment by MaciejG604** [comment]
Hi @cebaraldi, the command fails since the dependency specified has the `_3` Scala version suffix. The suffix is added since in the dependency name you've used a double colon `::` which says that a dependency is a Scala dependency. However, what you're looking for is a Java dependency so a single colon `:` should be specified.

Correct syntax would be:
`scala-cli repl --scala 3.3.1 --dep commons-net:commons-net:3.10.0`

**Comment by cebaraldi** [comment]
Hello Maciej Gajek,

thank you for the hint. The syntax using colon or double colons is a bit
cryptic. I should have invested more time to look it up properly.

Regards,
Claudio

**Comment by tgodzik** [comment]
The discussion is in https://github.com/VirtusLab/scala-cli/discussions/2628
