### ISSUE TITLE
Any plan to include Intellij plugin to recognise scala cli code?

### ISSUE THREAD

**Issue by gvlpedro** [VirtusLab/scala-cli#2695]
**Is your feature request related to a problem? Please describe.**
We are using scala-cli to deploy cloud resources but Intellij is not recognise scala-cli code so it is difficult to have arguments with the rest of the team to use this tool.

**Describe the solution you'd like**
A good Intellij interoperability.

**Comment by bishabosha** [comment]
did you follow [the documentation](https://scala-cli.virtuslab.org/docs/commands/setup-ide)? is there more information about what isn't working as expected, is anything working?

**Comment by gvlpedro** [comment]
I executed scala-cli setup:

``` scala-cli setup-ide . --scala 2.12.14  ```

I included following code in Intellij:

```
//> using scala "2.12.14"
//> using lib "com.typesafe:config:1.4.3"

import com.typesafe.config._
```

Running from Intellij is not working and the import is in red colour, it does not recognise com.typesafe dependency however it works when I use the terminal:

```scala-cli setup-ide . --scala 2.12.14 ```

**Comment by Gedochao** [comment]
Did you import your project via BSP?

<img width="730" alt="image" src="https://github.com/VirtusLab/scala-cli/assets/18601388/b52d7635-25e7-4359-bb0a-dcdd466bf7ba">

If you create an IntelliJ project and only later run `scala-cli setup-ide`, IntelliJ may not recognise that it should create a BSP connection. You may have to add it manually, or else reimport the project.

Do you have scripts in your sources? There's a bunch of things which aren't supported tied to Scala CLI scripts. Basically, IntelliJ treats them as worksheets, instead of scripts. Not to mention shebang isn't recognised.
See: https://github.com/VirtusLab/scala-cli/issues/2656

However, regular `.scala` files should work nicely. If it's not script related, you might try refreshing BSP connection (there's a button for it in the BSP tag). In extreme cases, killing the BSP connection and starting it again might help as well, but that shouldn't be necessary.

<img width="1402" alt="image" src="https://github.com/VirtusLab/scala-cli/assets/18601388/c9aff869-d369-4bb5-a0bc-088af1554298">

@gvlpedro I am able to import the code you provided into IntelliJ without any issue.
If it's still not working for you, we need more information on your project setup, as there's not much to go on on what may not be working for you.

Overall, Scala CLI projects should successfully import to IntelliJ via BSP.

**Comment by Gedochao** [comment]
Also, we do have IntelliJ-specific documentation, the guides and cookbooks should be up-to-date.
https://scala-cli.virtuslab.org/docs/guides/introduction/ide#intellij
https://scala-cli.virtuslab.org/docs/cookbooks/ide/intellij/

**Comment by gvlpedro** [comment]
thank you @Gedochao , my script is included in a SBT project with some submodules and I use the script to deploy, let me read all documentation

**Comment by Gedochao** [comment]
> my script is included in a SBT project with some submodules and I use the script to deploy, let me read all documentation

https://scala-cli.virtuslab.org/docs/cookbooks/ide/intellij-sbt-with-bsp
We actually have a dedicated cookbook for setting up a Scala CLI BSP module alongside your SBT project in IntelliJ.
Let me know if everything works.

**Comment by gvlpedro** [comment]
Amazing, now it is working, thank you !!!

**Comment by DavidPerezIngeniero** [comment]
> Amazing, now it is working, thank you !!!

Does it recognize using directives? In my case, it doesn't.
