### ISSUE TITLE
Cannot always print help from compiler

### ISSUE THREAD

**Issue by lrytz** [VirtusLab/scala-cli#2779]
Version 1.1.3

Using `-X` is ok, but `-Xlint:help` not.

```
➜ sandbox scala-cli compile -S 2 -X
Usage: scalac <options> <source files>

Available advanced options:
  -Xasync                          Enable the async phase for scala.async.Async.{async,await}. [false]
...


➜ sandbox scala-cli compile -S 2 -Xlint:help
[error]  No inputs provided (expected files with .scala, .sc, .java or .md extensions, and / or directories).
➜ sandbox
```

It works when using plain `scala-cli` without the `compile` subcommand.

**Comment by lrytz** [comment]
Related to https://github.com/VirtusLab/scala-cli/issues/753

**Comment by Gedochao** [comment]
This is caused by the fact that printing (help) options from the compiler currently need to be hard-tagged as such in the CLI code, otherwise the CLI will still require inputs to be passed, as it doesn't know a build won't be necessary.

We should be able to solve this (and other problems) permanently for Scala 3 compiler options after https://github.com/scala/scala3/pull/19766 gets released.
Something similar could be possible for Scala 2 options, if we had the API somewhere.

**Comment by Gedochao** [comment]
@lrytz as a workaround, you can just pass dummy inputs alongside `-Xlint:help` to get the output.

```bash
scala-cli compile -e 'println("dummy")' -S 2 -Xlint:help
# Compiling project (Scala 2.13.13, JVM (17))
# Enable recommended warnings
#   adapted-args            An argument list was modified to match the receiver.
#   nullary-unit            `def f: Unit` looks like an accessor; add parens to look side-effecting.
#   (...)
# Default: All choices are enabled by default.
# Error compiling project (Scala 2.13.13, JVM (17))
# Compilation failed
```
The `Compilation failed` message may be confusing, this is because the CLI assumed the compiler would, well, compile, rather than print help.

**Comment by lrytz** [comment]
> @lrytz as a workaround, you can just pass dummy inputs

Or not use the `compile` subcommand, e.g., `scala-cli -S 2 -opt:help`.
