### ISSUE TITLE
Scala CLI should produce warnings inproper for dependencies declaration

### ISSUE THREAD

**Issue by romanowski** [VirtusLab/scala-cli#285]
There are several situations that are supported but can be misleading and Scala CLI should report a warning in such a case.

The list of such situations:
- [x] ~~mixed syntaxes (using directives and Ammonite syntax)~~
- [x] duplicated definitions https://github.com/VirtusLab/scala-cli/issues/1833
- [x] definitions inside many files (more then 3), with suggestion to migrate dependencies declaration to single one
- [x] target directives are not defined o top of dependencies (or other configuration)  https://github.com/VirtusLab/scala-cli/issues/1838

**Comment by przemek-pokrywka** [comment]
For directives in more than one file I would go for a hard error instead of a warning. 

That's because otherwise we'd need to expect all sorts of mess ensuing, in bug reports and in other places.

I'd recommend everyone to keep the directives in one of the following places:
- in the program's entry point
- in a designated program.scala.conf file
- in both of the above, config overriding the hardcoded stuff
