### ISSUE TITLE
unable to generate code coverage using scoverage in scala-cli

### ISSUE THREAD

**Issue by MuthuVignesh91** [VirtusLab/scala-cli#2945]
**Version(s)**
scala-cli --version
Scala CLI version: 1.3.1
Scala version (default): 3.4.1

**Describe the bug**
Running the test command like below
"scala-cli test <path to your scala tests>

unable to see the coverage report. Using ScalaTest as test framework. I couldn't find any options to generate the coverage report or integrate with scoverage tool in the "scala-cli test --full-help" command as well

**To Reproduce**
just try and run the test command as mentioned above

**Expected behaviour**
expecting to see coverage data generated.

**Comment by Gedochao** [comment]
@MuthuVignesh91 It's not shown under `--full-help`, because it's a Scala compiler option, not a Scala CLI option.
Try `--scalac-help` instead.
```bash
scala-cli compile --scalac-help 2>&1 |grep coverage
# -coverage-exclude-classlikes  List of regexes for packages, classes and modules
#                              to exclude from coverage.
#      -coverage-exclude-files  List of regexes for files to exclude from
#                               coverage.
#                -coverage-out  Destination for coverage classfiles and
```

You can pass the appropriate option to specify where the coverage report should be generated.
```scala
//> using dep org.scalatest::scalatest::3.2.18
//> using options -coverage-out:./coverage
import org.scalatest.flatspec.AnyFlatSpec

class TestSpec extends AnyFlatSpec {
  "A test" should "be run" in {
    assert(true === true)
  }
}
```

The coverage report gets generated under the specified path.
```bash
tree coverage
# coverage
# ├── scoverage.coverage
# └── scoverage.measurements.14ad86df-2001-4edd-b0a1-2b6a48d1b240.1
# 
# 1 directory, 2 files
```

EDIT:
You can also refer to Scala 3 docs: https://dotty.epfl.ch/docs/internals/coverage.html
