### ISSUE TITLE
Scope of scala-cli

### ISSUE THREAD

**Issue by sjrd** [VirtusLab/scala-cli#31]
It hasn't been a month, and there are already more issues about "features" than I think scala-cli should ever have. At the last meeting we already had some (inconclusive) discussions about what should or should not go in. It is not sustainable to have a debate about every individual feature.

We need to define one clear criteria against which we can weigh potential features, in order to determine whether they are in the scope of scala-cli or not.

We will probably have to discuss this in a live meeting, but it should also be put in a written form that we can refer to, hence this issue.

**Comment by sjrd** [comment]
To bootstrap the conversation, here is my proposal for a criteria:

> The scope of scala-cli stops where diverging choices of good options, or of no option at all, emerge based on varying use cases.

In other words, scala-cli contains *unavoidable* stuff. The stuff that, if you write Scala code, you will inevitably have to do, and in only one possible way. As soon as there are things that you may not need in some use cases, or where several good options exist, this is where you reach for an actual build tool, which will give you the power of choice that you need.

Here are some features that weigh positively against that criteria:

* Compiling: yeah, no kidding, if you write Scala code, you've got to compile it, and the only good option to do so is scalac with the right version.
* Running: you need to run the program, and the only good option to do so is to use the appropriate underlying runtime (JVM, JS, none for Native)
* Testing: already *somewhat* borderline, but it can be argued that everyone needs *some* tests. Test frameworks have several options, but they all work behind sbt-testing-interface, so the latter is the only good choice to execute tests.
* Resolving dependencies: everyone needs dependencies, if only the standard library, and the only good choice to resolve dependencies is through the Maven ecosystem.

Here are some features that weigh negatively against that criteria:

* Publishing: specific to the library use case; as long as you only write apps, you never need this.
* Cross-compiling: specific to the library use case.
* Cross-platform: not everyone needs that.
* Scalafix: not universal either.
* Configurable set of source file depending on "stuff": related to cross-compilation or cross-platform, clearly not necessary in all cases. Also, there isn't a single good choice to do this, so options diverge as soon as you want to do this.
* Packaging: use-case-specific. There are plenty of use cases where running from the scala-cli runner is enough. Also, there are competing good choices (a jar with dependencies; a fat jar; a native runner; etc.)

Some things can still be in a gray area, for example:

* scalafmt: it is not strictly necessary, but it is definitely the only good choice if you want to do it. It could be a "political" move to "force" everyone to use scalafmt.

If you have comments about this proposal, please tell whether:

* you're commenting about the *criteria* itself, in which case please provide your own proposal for a clear scope criteria, or
* you're commenting on my categorization of one of the features against my proposed criteria.

**Comment by przemek-pokrywka** [comment]
I find the presented categorization really useful to fend against feature creep - thanks @sjrd. I feel that the categorization follows from the stated purpose of the tool:
> Scala CLI is an experimental tool to run/compile/test Scala that aims at being a better scala command

I would only want to make a point, that "being a better scala command" would ideally follow from something even more high-level. I would propose to try to hold `scala-cli` to the following principles:

The tool aspires to:
- [simplify Scala getting started experience](https://contributors.scala-lang.org/t/proposal-simplifying-the-scala-getting-started-experience/2978)
- play well with other members of the ecosystem: IDEs/editors, build tools in particular

(by the way, that would be in the spirit of commenting about the *criteria* themselves - sort of refinement of the proposal)

Why do I think this is important? It is because we don't want to lose the big picture. It is correct, that several good options exist for some features (e.g. packaging). So a naive approach would be to simply leave the feature out. But if we want to actually simplify Scala getting started experience, then (IMO) we should take care, that the users know the upgrade paths.

So for example, if we leave out packaging, then let's also make sure, that `scala-cli` lets the user extract the necessary information easily: where the compiled classes are, how are they structured, maybe provide a working classpath variable value. An excellent example of doing this right is Coursier. It can be used to provide a classpath for a dependency when one calls it `cs fetch -p org.scalaz::scalaz-core:7.2.7` so people can call `java -cp $(cs fetch -p ...) ...`.

**Comment by romanowski** [comment]
I agree that feature creep is a real thread but on the other side, under-features will mark Scala CLI as tools only for beginners and scripting. 

To find a balance between feature creep and being underfeatured we are thinking in terms of the use cases for Scala CLI. So far we committed to the following use cases:
- Education
- Scripting
- Prototyping
- Small, single module project (e.g. command-line tools, simple web services etc.)

I think the discussion here should be scoped alongside 2 lines: should scala-cli support given use cases and if a given feature is required to properly support any of the supported use cases.

**Comment by romanowski** [comment]
Let's move the this discussion to discussions: https://github.com/VirtusLab/scala-cli/discussions/279
