### ISSUE TITLE
Noticable pause on initial `scala-cli --version`

### ISSUE THREAD

**Issue by scarf005** [VirtusLab/scala-cli#3123]
**Version(s)**

```
Scala CLI version: 1.4.3
Scala version (default): 3.4.2
```

**Describe the bug**

After running `scala-cli --version`, its version are printed out immediately with noticable pause doing nothing.

**To Reproduce**

[![asciicast](https://asciinema.org/a/qQCa4YFohGYy0LwsK5OgjqUFa.svg)](https://asciinema.org/a/qQCa4YFohGYy0LwsK5OgjqUFa)

1. run `scala-cli --version`
2. it takes around ~1s
3. run `scala-cli --version` again
4. the second run takes around ~200ms

**Expected behaviour**

`scala-cli --version` takes same time to finish regardless of which path it was invoked on as `--version` is not related to per-path configuration.

**Comment by Gedochao** [comment]
This is because the `version` sub-command checks if the currently used version is the newest one.
You can get rid of the delay by skipping that with the `--offline` option.
```bash
scala-cli --version --offline
scala-cli version --offline
```
This delay should also be absent from Scala CLI when used as the `scala` command with Scala 3.5.0+ installations (because it doesn't make sense to check for the newest Scala CLI there, it's paired with the compiler version anyway).

Closing this, nothing to be done.

**Comment by bishabosha** [comment]
I think apple also does some quarantine checking thing if you are on macOS but its only the first time

**Comment by scarf005** [comment]
It's recorded in ubuntu 22.04.

**Comment by kubukoz** [comment]
I'm still seeing this pause in `--version`, but `version` is instant. This is on macOS (m1 max) and not only on the first time.
