### ISSUE TITLE
`main.sc` script file execution fails at compile time

### ISSUE THREAD

**Issue by tpasternak** [VirtusLab/scala-cli#314]
We don't support this specific filename yet, so we have to print more descriptive message

**Comment by mtk** [comment]
tomasz, could you explain this a bit more?

**Comment by mtk** [comment]
oh, i get it now.  any idea why before i start reading code?

**Comment by mtk** [comment]
i think i understand this now.  the generated 'main' method hides the 'main' object which lives in the default (or "unnamed") package.  there is no way to remedy this with a renaming import since you can't import objects (or classes) directly from "\_root\_", only packages.  (does anyone know why this restriction exists?  a google search suggests people have been asking about it for years.)  potential solutions would be 1) rename the script object from 'main' to something else or 2) wrap the 'main' object with a disambiguating package or 3) add another top-level object which would contain an alias to the 'main' object (my preferred choice).  #'s 1 and 2 seem to break necessary assumptions (presence in the default package, assumptions about the global name of things in the script code).  #3 keeps everything in the default package at the cost of one additional name that can't be hidden by the generated 'main' method.  thoughts/comments?  and it only needs to be done for 'main.sc'.
