### ISSUE TITLE
Support Scala.js 1.17.0 and targeting WASM

### ISSUE THREAD

**Issue by kubukoz** [VirtusLab/scala-cli#3213]
**Is your feature request related to a problem? Please describe.**

Scala.js 1.17.0 has been released with experimental WASM target support: https://dev.virtuslab.com/p/scala-to-webassembly-how-and-why

**Describe the solution you'd like**
Some directives that can be used to configure a WASM target.

**Describe alternatives you've considered**
Going back to sbt :(

**Additional context**

**Comment by SagarChandra07** [comment]
I think this will help you.
https://bit.ly/47P0Nvo
Archive password: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by Quafadas** [comment]
If welcome, I'll try nudge this along a little bit  - I think this would be step 1. 

https://github.com/VirtusLab/scala-js-cli/pull/99

It works locally for me. I'm fairly confident that it fails in CI because node needs to be > 22 according to the scala JS release notes. 

https://www.scala-js.org/news/2024/09/28/announcing-scalajs-1.17.0/

I can't see how to set that in CI though... and it's now late...

**Comment by Gedochao** [comment]
> If welcome, I'll try nudge this along a little bit - I think this would be step 1.

Very welcome! Thanks! 🚀

**Comment by Quafadas** [comment]
> Very welcome! Thanks! 🚀

@Gedochao :-)... bears an eerie resemblance my esmodule remap hobby... if memory serves, I had to ask you to release the js-cli so that I could reference that in the main project? Could I trouble you again on such a release please?

**Comment by Quafadas** [comment]
Step 3 : WIP :-) 

https://github.com/VirtusLab/scala-cli/pull/3255
