### ISSUE TITLE
Create a way to only move to newer versions of Scala after approval

### ISSUE THREAD

**Issue by tgodzik** [VirtusLab/scala-cli#3233]
**Is your feature request related to a problem? Please describe.**
If a certain version of Scala is broken and the user uses `//> using scala 3` it might download that broken version of Scala.

**Describe the solution you'd like**
Only allow for specific version that we checked before.

**Describe alternatives you've considered**
We could make the Scala 3 release 2 stage same as with Scala 2

**Additional context**
The whole conundrum with Scala 3.6.0

**Comment by SethTisue** [comment]
Agree that it would be best if scala-cli didn't pick up new Scala versions until they are announced, rather than as soon as they are published. But I'm not sure how it could be accomplished.

> We could make the Scala 3 release 2 stage same as with Scala 

Hmm. But scala-cli actually has this issue equally with regards to both Scala 3 and Scala 2. So, not sure what you mean here.

Perhaps you are alluding to an not-really-related suggestion I made recently. In the Scala 2 release steps, automation stages a release, then manual intervention is required to actually publish it to Maven Central. It might be wise for the Scala 3 process to do that as well. But the goal would be to prevent accidents. Adding a manual step would not address the timing of when scala-cli picks it up, as several days (typically 48–72 hours) still pass after publication but before everything else is in place and the release is announced.
