### ISSUE TITLE
Cookbook: formatting the code

### ISSUE THREAD

**Issue by romanowski** [VirtusLab/scala-cli#333]
A simple cookbook that will show how to use formatting with Scala CLI. It should include:
- basic run of `fmt` command
- how to create a simple configuration file for Scalafmt (including links to full docs on Scalafmt page)

**Comment by ganeshchand** [comment]
I can work on it. Please feel free to assign it to me.

**Comment by lwronski** [comment]
@ganeshchand Please let us know if you need any help.

**Comment by sierikov** [comment]
Hi, @ganeshchand are you still working on it, or I can take this issue? If yes, @lwronski what difference must the cookbook have in comparison to `commands/format`? I have a basic draft now, but it is too similar to the `commands` section. Also, I'm stuck with `-F` and `--scalafmt-arg` flags. Can you please say if one of the following is a correct and expected syntax:

```bash
scala-cli fmt -F "maxColumnWidth=100" -F "newlines.sometimesBeforeColonInMethodReturnType=true" .
```

or

```bash
scala-cli fmt -F "maxColumnWidth=100,newlines.sometimesBeforeColonInMethodReturnType=true" .
```

**Comment by Gedochao** [comment]
@sierikov `-F` isn't for passing the configuration, it's for passing `scalafmt` options directly.
In other words
```bash
scala-cli fmt -F -help
```
is the equivalent to
```bash
scala-cli fmt --scalafmt-help
```

To pass the configuration string directly, you can use `--scalafmt-conf-str`.

I suspect you're free to take this, since we haven't heard from @ganeshchand in a long while.

> what difference must the cookbook have in comparison to commands/format

I'm not sure if we really still need a cookbook, but having one wouldn't hurt.
I'd imagine it would be a more step by step guide to using the tool, explaining how the configuration file is generated, but can also be saved and later modified, explaining each of the more niche options, and so on.
For inspiration, make sure to check:
```bash
scala-cli fmt --full-help --power
```
Also, instead of a cookbook, you might as well expand the existing `commands/format` doc.

**Comment by sierikov** [comment]
I have opened a pull request with my initial intuition. Please have a look and say what you think. Is maybe it more intuitive to move/duplicate some sections in `command/format`?

**Comment by ganeshchand** [comment]
@sierikov My apologies. This fell off my radar. Thank you taking over this.
