### ISSUE TITLE
`using_directives` parser crashes on `*/*/Foo.scala`

### ISSUE THREAD

**Issue by prolativ** [VirtusLab/scala-cli#3374]
**Version(s)**
1.5.4

**Describe the bug**
Using a nested wildcard (`*/*/...`) in `exclude` directive results in a crash caused by `java.lang.ArrayIndexOutOfBoundsException`

**To Reproduce**
Having the following project structure:
* ./project.scala:
```scala
//> using exclude */*/Foo.scala
```

* ./dir1/dir2/Foo.scala:
```scala
val foo // invalid code
```
Try to compile the project:
```shell
scala-cli compile .
```
**Expected behaviour**
Should not crash. Also the invalid file `Foo.scala` should be excluded from compilation sources and the compilation should succeed

**Comment by Gedochao** [comment]
So it turns out this isn't an `--exclude` issue at all.
it's the `using_directives` parser that breaks on `//> using exclude */*/Foo.scala`
The workaround is to wrap the directive value in double quotes:
```scala
//> using exclude "*/*/Foo.scala"
```

Of course, it's mainly the exclusion feature that ends up affected, since we don't use this sort of syntax elsewhere.
