### ISSUE TITLE
Properly handle using directives in scala-cli

### ISSUE THREAD

**Issue by romanowski** [VirtusLab/scala-cli#561]
As for now, our integration with using directives is not perfect namely:
- we should properly handle directives other then string (numerical and binary) in all our process (probably enforce it within API somehow). Where it makes sense we should support it (e.g. numerical for Scala version) and where not we should fail  with proper error message
- we should report proper errors for directives that does not parse (properly handle reporter from using direcectives)
- using directives should print proper positions

**Comment by lwronski** [comment]
As since https://github.com/VirtusLab/scala-cli/pull/1637 was merged it covers points from this issue:

> we should properly handle directives other then string (numerical and binary) in all our process (probably enforce it within API somehow). Where it makes sense we should support it (e.g. numerical for Scala version) and where not we should fail with proper error message

- now the case class represents the use of directive definitions where we can define parameter types

> we should report proper errors for directives that does not parse (properly handle reporter from using direcectives)

- for example was added mechanism do detect unclosed string literals https://github.com/VirtusLab/scala-cli/issues/906
