### ISSUE TITLE
cats-effect IO.unsafeRunSync doesn't appear to run

### ISSUE THREAD

**Issue by jisantuc** [VirtusLab/scala-cli#755]
**Version(s)**

1.0.2, 1.0.0 (haven't tried 1.0.1)

**Describe the bug**

`unsafeRunSync()` from cats-effect hangs in Scala 2.13.

I'm having trouble convincing myself the bug can live anywhere other than scala-cli, since in the example below:

- there's nothing going on except the IO calls
- `unsafeRunSync` is a sufficiently core cats-effect method that I think it can be assumed to work
- I tried cats-effect versions 3.3.0 through 3.3.6 and observed the same behavior

In Scala 3, `IO(println("foo"))` executes fine

**To Reproduce**

Here's a minimal reproducing example:

```scala
//> using scala "2.13"
//> using lib "org.typelevel::cats-effect:3.3.6"

import cats.effect.IO
import cats.effect.unsafe.implicits.global

println("I'm a println")
IO(println("I'm an IO")).unsafeRunSync()
```

**Expected behaviour**
IOs run, "I'm an IO" gets printed

**Comment by alexarchambault** [comment]
That looks like an issue with the object wrapper that Scala CLI generates. The code above gets compiled as something like
```scala
object foo {
  import cats.effect.IO
  import cats.effect.unsafe.implicits.global

  println("I'm a println")
  IO(println("I'm an IO")).unsafeRunSync()
}
```

Such a call in an object creates a deadlock in Scala 2.13 (can't find references for it right now…). Ammonite can work around this by [wrapping user code in classes](https://github.com/com-lihaoyi/Ammonite/pull/736) rather than objects (can be enabled with `--class-based`), but we don't support that in Scala CLI, and I'm not sure we'll ever support (the semantics of `*.sc` files in Scala CLI prevent it somehow…)

**Comment by alexarchambault** [comment]
As a workaround in Scala CLI, things can be manually put in a class for example:
```scala
//> using scala "2.13"
//> using lib "org.typelevel::cats-effect:3.3.6"

import cats.effect.IO
import cats.effect.unsafe.implicits.global

class Foo {
  def foo(): Unit = {
    println("I'm a println")
    IO(println("I'm an IO")).unsafeRunSync()
  }
}

(new Foo).foo()

```

**Comment by jisantuc** [comment]
Ah indeed thanks! Since the workaround is pretty straightforward and it's not trivially fixable, I'll close
